version: "3"
services:
  banking-app-server-service:
    platform: linux/amd64
    build: ./server
    container_name: banking-app-server
    restart: unless-stopped
    environment:
      MONGO_URI: "mongodb+srv://jeanlmenta:Gugqeb-6cogme-vixmej@bankingdb.vqj39qv.mongodb.net/?retryWrites=true&w=majority"
    networks:
      - your-app-network
    ports:
      - "3001:3001"

networks:
  your-app-network:
    driver: bridge
